services:
  backend:
    restart: always # 꺼지면 재시작
    container_name: greeneye-backend
    build: ./backend # greeneye/backend 경로에 있는 Dockerfile로 이미지 빌드
    env_file:
      - ./backend/.env.production
    depends_on:
      - mosquitto
    networks:
      - global_network

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: greeneye-mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    networks:
      - global_network

  frontend:
    restart: always # 꺼지면 재시작
    container_name: greeneye-frontend
    build: ./frontend # greeneye/backend 경로에 있는 Dockerfile로 이미지 빌드
    networks:
      - global_network
  


networks:
  global_network:
    external: true

volumes:
  mosquitto_data:
  mosquitto_log: