#!/usr/bin/env bash
# GREENEYE: 서버 홈(또는 상위)의 통합 .env.production에서 값을 읽어
# backend / frontend 빌드·런타임용 env 파일을 생성합니다.
#
# 사용 (greeneye 디렉터리에서):
#   chmod +x scripts/prepare-env.sh
#   ./scripts/prepare-env.sh
#   ./scripts/prepare-env.sh ../.env.production
#
# 기본 경로: <greeneye 상위 디렉터리>/.env.production
# 예: /root/.env.production + /root/greeneye

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# 인자 없음: <greeneye 상위>/.env.production
# 인자 있음: ../.env.production 처럼 **현재 작업 디렉터리(cwd)** 기준 (clone 후 cd greeneye 에서 실행 가정)
if [[ -n "${1:-}" ]]; then
  ROOT_ENV="$1"
else
  ROOT_ENV="$PROJECT_ROOT/../.env.production"
fi

if [[ ! -f "$ROOT_ENV" ]]; then
  echo "prepare-env: env 파일을 찾을 수 없습니다: $ROOT_ENV"
  echo "  (greeneye 폴더에서 ./scripts/prepare-env.sh ../.env.production 형태로 실행했는지 확인하세요)"
  exit 1
fi

# 절대 경로로 정규화 (상대 경로는 cwd 기준)
ROOT_ENV="$(cd "$(dirname "$ROOT_ENV")" && pwd)/$(basename "$ROOT_ENV")"

set -a
# shellcheck disable=SC1090
source "$ROOT_ENV"
set +a

: "${GOOGLE_CLIENT_ID_GREENEYE:?prepare-env: GOOGLE_CLIENT_ID_GREENEYE 가 $ROOT_ENV 에 없습니다}"
: "${GREENEYE_GEMINI_API_KEY:?prepare-env: GREENEYE_GEMINI_API_KEY 가 $ROOT_ENV 에 없습니다}"
: "${DB_PASSWORD:?prepare-env: DB_PASSWORD 가 $ROOT_ENV 에 없습니다}"

DB_USERNAME="${DB_USERNAME:-gwon}"
MQTT_BROKER_URL="${MQTT_BROKER_URL:-tcp://gwon-mosquitto:1883}"
MQTT_CLIENT_ID="${MQTT_CLIENT_ID:-greeneye-backend}"
VITE_API_BASE_URL="${VITE_API_BASE_URL:-/api}"

umask 077

cat > "$PROJECT_ROOT/backend/.env.production" <<EOF
# generated by scripts/prepare-env.sh — do not commit
DB_USERNAME=${DB_USERNAME}
DB_PASSWORD=${DB_PASSWORD}
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID_GREENEYE}
GEMINI_API_KEY=${GREENEYE_GEMINI_API_KEY}
MQTT_BROKER_URL=${MQTT_BROKER_URL}
MQTT_CLIENT_ID=${MQTT_CLIENT_ID}
EOF

cat > "$PROJECT_ROOT/frontend/.env.production" <<EOF
# generated by scripts/prepare-env.sh — do not commit
VITE_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID_GREENEYE}
VITE_API_BASE_URL=${VITE_API_BASE_URL}
EOF

chmod 600 "$PROJECT_ROOT/backend/.env.production" "$PROJECT_ROOT/frontend/.env.production" 2>/dev/null || true

echo "prepare-env: OK"
echo "  backend:  $PROJECT_ROOT/backend/.env.production"
echo "  frontend: $PROJECT_ROOT/frontend/.env.production"
echo "  source:   $ROOT_ENV"
