spring:
  autoconfigure:
    exclude:
      - io.awspring.cloud.autoconfigure.s3.S3AutoConfiguration
  datasource:
    url: jdbc:mysql://gwon-db:3306/greeneye?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update # 엔티티 변경사항을 DB에 자동 반영 (핵심!)
    properties:
      hibernate:
        format_sql: true
        show_sql: true

google:
  client:
    id: ${GOOGLE_CLIENT_ID}

gemini:
  api:
    key: ${GEMINI_API_KEY}

mqtt:
  broker-url: ${MQTT_BROKER_URL:tcp://gwon-mosquitto:1883}
  client-id: ${MQTT_CLIENT_ID:greeneye-backend}